---
title: "monty"
author: "Justeen Cook"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
 
library(devtools)
library(roxygen2)
library(usethis)
library(testthat)
library(knitr)

```

```{r}
# devtools::create_package() has been deprecated
# set your directory
# setwd()
usethis::create_package( "montyhall" )
```

```{r}
#' @title
#' Sum of vector elements.
#'
#' @description
#' `sum(x)` returns the sum of all the values present in its arguments.
#'
#' @details
#' This is a generic function: methods can be defined for it directly
#' or via the [Summary] group generic. For this to work properly,
#' the arguments `...` should be unnamed, and dispatch is on the
#' first argument.
#'
#' @param x Numeric, complex, or logical vectors.
#' @param na.rm A logical scalar. Should missing values (including `NaN`)
#'   be removed?
#' @return If all inputs are integer and logical, then the output
#'   will be an integer. Otherwise it will be a length-one numeric or
#'   complex vector.
#'
#'   Zero-length vectors have sum 0 by definition. See
#'   <http://en.wikipedia.org/wiki/Empty_sum> for more details.
#'
#' @examples
#' sum(1:10)
#' sum(1:5, 6:10)
#' sum(F, F, F, T, T)
#'
#' sum(.Machine$integer.max, 1L)
#' sum(.Machine$integer.max, 1)
#'
#' \dontrun{
#' sum("a")
#' }
sum <- function(..., na.rm = TRUE) {}
```


```{r}
setwd( "C:/Users/juste/Documents/montyhall" )
devtools::document()
```

```{r}
setwd( "C:/Users/juste/Documents" )
devtools::install( "montyhall" )
```




